### ISSUE TITLE
VS Code extension

### ISSUE THREAD

**Issue by kristiandupont** [filipesabella/CalcPad#16]
I saw your comment on Hacker News and I like your project! I would personally love to see it as an extension to VSCode. I feel that this would provide a nice complement to note books, and I could imagine having these "pad files" in repositories.

Obviously, this is just a suggestion, thank you for making your work open source!

**Comment by filipesabella** [comment]
On the theme of not getting any notifications on this repo 🤦‍♂️

Thanks for the comment and suggestion. Back in the day adding another calculated gutter element on vscode proved to be super hard and I gave up. Maybe it's easier now, but I don't see myself spending time on it.
