### ISSUE TITLE
Energy/power units are not supported

### ISSUE THREAD

**Issue by quaintdev** [filipesabella/CalcPad#17]
First of all, thank you for creating this.

I see that calcpad has dependency on convert-units. They support energy and power related units but for some reason if I try to use those units in calcpad the calculations fail. Any suggestions? 

I am using the web version.

**Comment by filipesabella** [comment]
Sorry for the ... 2 year delay on responding, I wasn't getting notifications for this repo.

Do you have an example?

**Comment by quaintdev** [comment]
I forgot about this too. I checked again today and I think it's working as expected. I probably had used incorrect syntax at the time. 

Any chance you can make docker image available for this? I think r/selfhosted community on Reddit would love it.

**Comment by filipesabella** [comment]
Thanks for the reply!

I don't wanna spend the day it'd take me to figure out how to publish a docker image with just a couple of static files, but a contribution would be immensely appreciated 🙏
